name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
Host my-vps
  HostName $SSH_IP
  User $SSH_USER
  IdentityFile ~/.ssh/deploy-key.pem
  StrictHostKeyChecking no
END
          cat ~/.ssh/config
          ls -la ~/.ssh/
          cat ~/.ssh/deploy-key.pem 
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
      
      - name: Test SSH connection
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }} && pwd'
        env:
          PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}

